export const packs = [
  {
    id: "russian-energy",
    title: "Russian energy",
    short: "How redirected flows, shadow fleets, and policy loopholes keep revenue resilient.",
    actor: "Russian state and energy ecosystem",
    region: "Europe / Global",
    cover: "/covers/russian-energy.webp",
    color: "#b64b35",
    movement: 18,
    confidence: 82,
    sources: 48,
    signals: 184,
    posture: "Strong",
    status: "moving",
    thesis: "Messaging that frames energy sanctions as futile or self-defeating can weaken political support for enforcement while obscuring the operational adaptations that preserve export revenue.",
    boundary: "The model estimates who is sensitive to policy outcomes. It does not assert that a beneficiary funded or promoted a narrative without direct evidence.",
    developments: [
      ["1h", "EU adds 14 tankers to sanctions list over Russia oil transport", "Policy", 72],
      ["2h", "India seeks alternative crude as discounts narrow", "Markets", 64],
      ["3h", "Lawmakers push bill targeting energy-sector enablers", "Policy", 58],
      ["6h", "Insurers review exposure to aging shadow-fleet vessels", "Risk", 55],
    ],
    history: [
      ["2022", "Sanctions shock", "Export restrictions create a high-salience economic story.", 68],
      ["2023", "Redirected flows", "Asian buyers and intermediaries become central to the narrative.", 76],
      ["2024", "Shadow-fleet focus", "Enforcement debate shifts to tankers, insurers, and services.", 81],
      ["Now", "Futility frame", "Policy friction is used to argue sanctions only harm consumers.", 88],
    ],
    forecast: [
      ["24 hours", 74, "New tanker designations drive rapid policy commentary."],
      ["7 days", 67, "Energy-price movement increases mainstream pickup."],
      ["30 days", 51, "Without a new shock, the story returns to specialist audiences."],
    ],
    capital: [
      ["Rosneft", "State-linked producer", "documented", 94, 88, 91, "Revenue and market-access sensitivity", "Export resilience and lower enforcement pressure would support realized revenue."],
      ["Sovcomflot", "Shipping company", "documented", 92, 84, 94, "Freight and fleet-utilization sensitivity", "Shipping restrictions and enforcement directly affect utilization scenarios."],
      ["Trading intermediaries", "Commodity services", "scenario", 67, 79, 42, "Arbitrage and fee opportunity", "More fragmented trade routes can increase intermediary demand and margins."],
      ["Marine insurers", "Financial services", "scenario", 54, 58, 65, "Premium and loss exposure", "Enforcement changes both premium opportunity and loss risk."],
      ["EU energy consumers", "Demand-side exposure", "scenario", 28, 41, 78, "Price sensitivity", "The narrative often foregrounds household and industrial cost exposure."],
    ],
    evidence: [
      ["EU sanctions against Russia explained", "Council of the European Union", "Counter-record"],
      ["Price cap coalition advisory for maritime oil industry", "U.S. Treasury", "Primary source"],
      ["Russian oil trade and shadow fleet analysis", "KSE Institute", "Context"],
      ["Sanctions implementation and circumvention reporting", "European Parliament", "Context"],
    ],
    nodes: [
      ["energy-frame", "Sanctions are futile", "narrative", 0, 0],
      ["state-media", "State media", "channel", -280, -120],
      ["policy-voices", "Political commentary", "channel", -280, 130],
      ["enforcement", "Enforcement pressure", "outcome", 270, -120],
      ["export-revenue", "Export revenue", "capital", 270, 120],
      ["shadow-fleet", "Shadow fleet", "entity", 0, 250],
    ],
    edges: [
      ["state-media", "energy-frame", "amplifies", "observed"],
      ["policy-voices", "energy-frame", "repeats", "observed"],
      ["energy-frame", "enforcement", "may weaken", "scenario"],
      ["enforcement", "export-revenue", "affects", "documented"],
      ["shadow-fleet", "export-revenue", "supports", "documented"],
    ],
  },
  {
    id: "biolabs",
    title: "Biolabs",
    short: "How real public-health laboratories are reframed as covert weapons infrastructure.",
    actor: "Russian state-aligned information ecosystem",
    region: "Global",
    cover: "/covers/biolabs.webp",
    color: "#778f83",
    movement: 24,
    confidence: 92,
    sources: 63,
    signals: 241,
    posture: "Strong",
    status: "moving",
    thesis: "A long-running narrative conflates documented U.S. support for Ukrainian public-health and threat-reduction laboratories with unsupported claims of a covert biological weapons program.",
    boundary: "The existence of laboratories and threat-reduction funding is documented. That does not establish a weapons program.",
    developments: [
      ["18m", "Recycled politician clip recirculates with a new date", "Reactivation", 91],
      ["2h", "State-media segment links declassification debate to Ukraine labs", "Broadcast", 78],
      ["5h", "Fact-checkers separate threat-reduction work from weapons claims", "Counter", 69],
    ],
    history: [
      ["Mar 2022", "Wartime surge", "Officials and state media frame public-health labs as weapons sites.", 74],
      ["Mar 2022", "Western pickup", "The framing enters political and podcast ecosystems.", 61],
      ["Dec 2024", "Recycled clip", "Older remarks are presented as a new development.", 38],
      ["Now", "Fresh trigger", "A real records debate reactivates the older allegation.", 86],
    ],
    forecast: [
      ["24 hours", 82, "Clips omit the distinction between laboratories and weapons programs."],
      ["7 days", 68, "Russian and PRC state media sustain cross-language coverage."],
      ["30 days", 42, "The story persists in established niche communities."],
    ],
    capital: [
      ["Russian strategic influence operations", "Strategic beneficiary", "scenario", 88, 79, 82, "Institutional distrust value", "Acceptance supports defensive-war framing and distrust of Western institutions."],
      ["Threat-reduction programs", "Public program", "documented", 63, 22, 94, "Political and funding exposure", "Public distrust can increase scrutiny of overseas biosecurity partnerships."],
      ["Attention-driven publishers", "Media revenue", "scenario", 52, 66, 31, "Audience and advertising opportunity", "High-conflict biosecurity content can create short-term attention value."],
    ],
    evidence: [
      ["Biological Threat Reduction Program Activities in Ukraine", "U.S. Department of Defense", "Primary source"],
      ["Social posts misrepresent U.S.-Ukraine threat reduction program", "FactCheck.org", "Counter-record"],
      ["China amplifies unsupported Russian claim of Ukraine biolabs", "Associated Press", "Observation"],
    ],
    nodes: [
      ["labs", "Public-health laboratories", "fact", -250, -120],
      ["weapons", "Covert weapons allegation", "narrative", 0, 0],
      ["officials", "Official claims", "channel", -260, 140],
      ["state-media", "State media", "channel", 260, -130],
      ["commentary", "Political commentary", "channel", 280, 120],
      ["distrust", "Institutional distrust", "outcome", 0, 250],
    ],
    edges: [
      ["labs", "weapons", "conflated with", "observed"],
      ["officials", "weapons", "asserts", "documented"],
      ["weapons", "state-media", "distributed by", "observed"],
      ["state-media", "commentary", "crosses into", "observed"],
      ["weapons", "distrust", "may increase", "scenario"],
    ],
  },
  {
    id: "peace-ultimatum",
    title: "Peace ultimatum",
    short: "How coercive conditions are reframed as peace offers and refusal is assigned to Kyiv.",
    actor: "Russian state-aligned information ecosystem",
    region: "Europe",
    cover: "/covers/peace-ultimatum.webp",
    color: "#a68a68",
    movement: 15,
    confidence: 87,
    sources: 39,
    signals: 148,
    posture: "Strong",
    status: "moving",
    thesis: "The frame recasts aggression as a failed peace process caused by Ukraine and its partners, especially around negotiations and aid decisions.",
    boundary: "Characterizing terms as a peace offer does not establish that rejection of those terms caused the war.",
    developments: [
      ["43m", "Negotiation commentary spikes after ceasefire statement", "Diplomacy", 83],
      ["4h", "Aid package described as obstacle to peace across aligned outlets", "Media", 76],
      ["8h", "Counter-analysis compares stated terms with territorial demands", "Counter", 63],
    ],
    history: [
      ["2022", "Invasion framing", "Responsibility is shifted toward NATO and Kyiv.", 72],
      ["2024", "Negotiation frame", "Military aid is recast as preventing peace.", 65],
      ["Now", "Ultimatum cycle", "Russian conditions are described as a peace offer.", 83],
    ],
    forecast: [
      ["24 hours", 73, "A negotiation or aid announcement provides a trigger."],
      ["7 days", 77, "Ceasefire talks remain unresolved."],
      ["30 days", 64, "The frame remains structurally reusable."],
    ],
    capital: [
      ["Sanctioned Russian banks", "Financial sector", "scenario", 72, 76, 67, "Sanctions-relief sensitivity", "A political shift toward relief could improve market access."],
      ["European defense suppliers", "Industrial sector", "scenario", 34, 29, 71, "Order-book downside", "Reduced military assistance could lower future order expectations."],
      ["Russian strategic influence operations", "Strategic beneficiary", "scenario", 86, 73, 81, "Responsibility-shifting value", "Acceptance can weaken political support for Ukraine."],
    ],
    evidence: [
      ["Victim-blaming Kyiv while dressing up Russia's ultimatum as a peace offer", "EUvsDisinfo", "Observation"],
      ["United Nations General Assembly resolutions on Ukraine", "United Nations", "Primary source"],
      ["EU sanctions against Russia explained", "Council of the European Union", "Context"],
    ],
    nodes: [
      ["terms", "Coercive terms", "fact", -250, -100],
      ["offer", "Peace-offer frame", "narrative", 0, 0],
      ["diplomacy", "Diplomatic channels", "channel", -250, 150],
      ["commentary", "Political commentary", "channel", 260, -120],
      ["support", "Support for Ukraine", "outcome", 270, 130],
      ["relief", "Sanctions relief", "capital", 0, 250],
    ],
    edges: [
      ["terms", "offer", "reframed as", "observed"],
      ["diplomacy", "offer", "distributes", "observed"],
      ["offer", "commentary", "enters", "observed"],
      ["offer", "support", "may weaken", "scenario"],
      ["support", "relief", "may affect", "scenario"],
    ],
  },
  {
    id: "covert-influence",
    title: "Covert influence",
    short: "How state narratives are made to appear like independent commentary.",
    actor: "Russian state media and influence operators",
    region: "Global",
    cover: "/covers/covert-influence.webp",
    color: "#748b9b",
    movement: 12,
    confidence: 96,
    sources: 71,
    signals: 312,
    posture: "Documented",
    status: "stable",
    thesis: "Publicly documented operations use covert funding, proxies, and distribution infrastructure to disguise state direction and increase credibility.",
    boundary: "Editorial alignment alone is not evidence of coordination. Attribution requires funding, infrastructure, behavior, or official evidence.",
    developments: [
      ["1h", "Platform removes newly attributed proxy-media network", "Platform", 75],
      ["5h", "Researchers map replacement domains after takedown", "Research", 67],
      ["12h", "Treasury designation cited in new policy hearing", "Policy", 44],
    ],
    history: [
      ["2020", "Ecosystem model", "Proxy sites and state media are described as reinforcing pillars.", 60],
      ["2024", "Covert attribution", "Treasury documents a covert operational role.", 88],
      ["Now", "Adaptive infrastructure", "Cross-platform replacement behavior persists.", 80],
    ],
    forecast: [
      ["24 hours", 59, "A high-salience event creates an opportunity window."],
      ["7 days", 66, "Replacement accounts and domains reconstitute distribution."],
      ["30 days", 72, "Operational infrastructure remains adaptive."],
    ],
    capital: [
      ["Proxy media operators", "Operational beneficiary", "documented", 91, 82, 88, "Funding and audience growth", "Covert funding and distribution can create direct operating value."],
      ["Video commentary publishers", "Media revenue", "scenario", 46, 63, 33, "Audience monetization", "Cross-platform pickup can increase reach and advertising opportunity."],
      ["Platforms", "Operational exposure", "documented", 68, 18, 91, "Detection and enforcement cost", "Disposable infrastructure increases moderation cost."],
    ],
    evidence: [
      ["Treasury exposes RT's covert global intelligence and influence operations", "U.S. Treasury", "Primary source"],
      ["Russia's pillars of disinformation and propaganda", "U.S. Department of State", "Context"],
      ["Fourth report on foreign information manipulation threats", "EEAS", "Context"],
    ],
    nodes: [
      ["funding", "Covert funding", "capital", -260, -120],
      ["proxy", "Proxy publisher", "entity", 0, 0],
      ["influencer", "Independent-presenting voice", "channel", 270, -120],
      ["platform", "Video platform", "channel", 270, 140],
      ["state", "State direction", "entity", -260, 140],
      ["audience", "Target audience", "outcome", 0, 250],
    ],
    edges: [
      ["state", "funding", "directs", "documented"],
      ["funding", "proxy", "supports", "documented"],
      ["proxy", "influencer", "packages through", "documented"],
      ["influencer", "platform", "distributes on", "observed"],
      ["platform", "audience", "reaches", "observed"],
    ],
  },
  {
    id: "prc-discourse",
    title: "PRC discourse",
    short: "How content partnerships and official messaging reshape the information environment.",
    actor: "People's Republic of China information ecosystem",
    region: "Global",
    cover: "/covers/prc-discourse.webp",
    color: "#8d5b43",
    movement: 9,
    confidence: 86,
    sources: 54,
    signals: 122,
    posture: "Strong",
    status: "stable",
    thesis: "A broad state communications effort uses official messaging, state media, content partnerships, and platform distribution to promote preferred governance narratives.",
    boundary: "State-funded media activity is not automatically covert influence; disclosure and operational behavior matter.",
    developments: [
      ["2h", "Regional outlet republishes state-media technology feature", "Placement", 61],
      ["9h", "Diplomatic accounts converge on trade-sovereignty frame", "Official", 57],
      ["1d", "Researchers update content-partnership map", "Research", 48],
    ],
    history: [
      ["2017", "International expansion", "Content partnerships and global distribution expand.", 48],
      ["2023", "Environment assessment", "Public reporting documents a broad method set.", 78],
      ["Now", "Persistent infrastructure", "Cross-platform distribution continues.", 67],
    ],
    forecast: [
      ["24 hours", 48, "A trade or technology dispute creates a trigger."],
      ["7 days", 62, "Official accounts and partners sustain the frame."],
      ["30 days", 71, "Distribution relationships remain in place."],
    ],
    capital: [
      ["State-backed media partnerships", "Distribution network", "documented", 78, 64, 76, "Reach and legitimacy value", "Content-placement relationships can increase audience reach."],
      ["Telecom and platform vendors", "Commercial sector", "scenario", 42, 55, 47, "Market-access sensitivity", "Governance narratives may influence procurement or policy climates."],
    ],
    evidence: [
      ["How the PRC seeks to reshape the global information environment", "U.S. Department of State", "Context"],
      ["Global media freedom indicators", "Reporters Without Borders", "Counter-record"],
    ],
    nodes: [
      ["official", "Official messaging", "entity", -260, -100],
      ["state-media", "State media", "channel", 0, 0],
      ["partners", "Content partners", "channel", 260, -110],
      ["diplomats", "Diplomatic accounts", "channel", -260, 150],
      ["audience", "Regional audiences", "outcome", 270, 150],
      ["policy", "Policy climate", "outcome", 0, 250],
    ],
    edges: [
      ["official", "state-media", "sets frame", "documented"],
      ["state-media", "partners", "placed through", "observed"],
      ["diplomats", "state-media", "reinforces", "observed"],
      ["partners", "audience", "reaches", "observed"],
      ["audience", "policy", "may affect", "scenario"],
    ],
  },
  {
    id: "adaptive-fimi",
    title: "Adaptive FIMI",
    short: "Disposable domains, synthetic personas, and cross-platform replacement behavior.",
    actor: "Multiple foreign manipulation actors",
    region: "Global",
    cover: "/covers/adaptive-fimi.webp",
    color: "#6c7788",
    movement: 7,
    confidence: 90,
    sources: 44,
    signals: 98,
    posture: "Strong",
    status: "watch",
    thesis: "Foreign information manipulation operations increasingly use disposable and cross-platform infrastructure that survives individual account or domain removals.",
    boundary: "Shared framing is a discovery signal, not proof of coordination.",
    developments: [
      ["3h", "Replacement domains appear after coordinated takedown", "Infrastructure", 68],
      ["11h", "Synthetic persona cluster migrates to messaging apps", "Platform", 62],
      ["1d", "Threat report updates cross-platform behavior model", "Research", 45],
    ],
    history: [
      ["2023", "Cross-platform playbooks", "Operations are documented across multiple services.", 54],
      ["Now", "Adaptive infrastructure", "Disposable assets and proxies increase resilience.", 81],
    ],
    forecast: [
      ["24 hours", 55, "Takedown pressure triggers replacement activity."],
      ["7 days", 78, "A high-salience event creates an opportunity window."],
      ["30 days", 66, "Infrastructure remains useful across campaigns."],
    ],
    capital: [
      ["Platform trust and safety teams", "Operational exposure", "documented", 82, 12, 92, "Detection and enforcement cost", "Disposable infrastructure increases investigative workload."],
      ["Infrastructure resellers", "Service providers", "scenario", 38, 49, 28, "Short-lived service revenue", "Frequent replacement may increase demand for disposable infrastructure."],
    ],
    evidence: [
      ["Fourth EEAS report on foreign information manipulation threats", "EEAS", "Primary source"],
      ["DISARM framework", "DISARM Foundation", "Method"],
    ],
    nodes: [
      ["origin", "Campaign operator", "entity", -260, -100],
      ["domains", "Disposable domains", "channel", 0, 0],
      ["personas", "Synthetic personas", "channel", 260, -110],
      ["apps", "Messaging apps", "channel", -250, 150],
      ["audience", "Target audience", "outcome", 270, 150],
      ["cost", "Moderation cost", "capital", 0, 250],
    ],
    edges: [
      ["origin", "domains", "deploys", "documented"],
      ["domains", "personas", "coordinates with", "observed"],
      ["personas", "apps", "migrates to", "observed"],
      ["personas", "audience", "reaches", "observed"],
      ["domains", "cost", "increases", "scenario"],
    ],
  },
];

export const capitalRail = [
  ["Rosneft", "High exposure", "Revenue, market share", "#b64b35"],
  ["Sovcomflot", "High exposure", "Freight, fleet utilization", "#b64b35"],
  ["Trading houses", "Medium exposure", "Arbitrage, fees", "#b99a56"],
  ["Threat-reduction programs", "Political exposure", "Funding, trust", "#778f83"],
  ["Platforms", "Operational exposure", "Detection cost", "#748b9b"],
];

export const quickPrompts = [
  "Who benefits if the Russian energy futility frame is accepted?",
  "Trace the biolabs narrative into Western commentary",
  "Compare documented and scenario edges in covert influence",
];

export const techniques = [
  {
    id: "conflation",
    label: "Conflation",
    description: "Blends a documented fact with an unsupported conclusion so the claim inherits the fact's credibility.",
    example: "Public-health laboratories become evidence of a covert weapons program.",
    packIds: ["biolabs", "peace-ultimatum"],
  },
  {
    id: "victim-blaming",
    label: "Victim blaming",
    description: "Reassigns responsibility for aggression or coercion to the target and its partners.",
    example: "Rejecting coercive conditions is framed as refusing peace.",
    packIds: ["peace-ultimatum"],
  },
  {
    id: "covert-funding",
    label: "Covert funding",
    description: "Hides state direction behind independent-presenting publishers, creators, or intermediaries.",
    example: "Operational funding is separated from the public-facing media brand.",
    packIds: ["covert-influence", "adaptive-fimi"],
  },
  {
    id: "historical-revision",
    label: "Historical revision",
    description: "Selectively edits chronology or context to make a current action appear defensive or inevitable.",
    example: "Prior aggression is removed from the timeline used to explain the current event.",
    packIds: ["peace-ultimatum"],
  },
  {
    id: "economic-fatalism",
    label: "Economic fatalism",
    description: "Presents enforcement as inherently futile while foregrounding its cost to the enforcing coalition.",
    example: "Sanctions only hurt European consumers and can never constrain export revenue.",
    packIds: ["russian-energy"],
  },
  {
    id: "proxy-media",
    label: "Proxy media",
    description: "Routes a state-aligned frame through outlets that appear editorially independent.",
    example: "A state-media frame is republished without clear provenance.",
    packIds: ["covert-influence", "prc-discourse", "adaptive-fimi"],
  },
  {
    id: "clip-recycling",
    label: "Clip recycling",
    description: "Repackages an older statement or image as evidence of a new development.",
    example: "A 2022 clip is circulated as if it were recorded this week.",
    packIds: ["biolabs", "adaptive-fimi"],
  },
  {
    id: "cross-platform",
    label: "Cross-platform coordination",
    description: "Uses multiple services and replacement assets to sustain reach after moderation or rebuttal.",
    example: "Removed domains are replaced and redistributed through messaging apps.",
    packIds: ["covert-influence", "prc-discourse", "adaptive-fimi"],
  },
];

export const projects = [
  {
    id: "energy-enforcement",
    title: "Russian energy enforcement",
    summary: "Monitor tanker designations, insurer exposure, and political repetition of the sanctions-futility frame.",
    updated: "Updated 18 min ago",
    accent: "#b64b35",
    items: {
      Notes: ["Shadow fleet definitions", "Price-cap enforcement gaps", "Weekly policy memo", "Claims requiring source review"],
      Links: ["EU designation update", "Price Cap Coalition advisory", "KSE tanker tracker", "Parliament hearing"],
      Chats: ["Who gains from weak enforcement?", "Trace insurer exposure", "Forecast next trigger", "Separate fact from scenario"],
      Graphs: ["Kovalchuk neighborhood", "Shipping services cluster", "Policy-to-revenue path", "Sovcomflot relationships"],
    },
  },
  {
    id: "biolabs-reactivation",
    title: "Biolabs reactivation map",
    summary: "Track recycled clips, source mutations, and entry points into Western political commentary.",
    updated: "Updated 41 min ago",
    accent: "#778f83",
    items: {
      Notes: ["Documented lab program", "Unsupported weapons claim", "Clip provenance", "Counter-record language"],
      Links: ["DoD threat-reduction record", "FactCheck counter-record", "AP amplification report", "Archive of original clip"],
      Chats: ["Find earliest reactivation", "Compare claim mutations", "List Western amplifiers", "Build evidence boundary"],
      Graphs: ["Claim lineage", "Cross-language pickup", "Commentary bridge", "Public-health entities"],
    },
  },
  {
    id: "covert-influence",
    title: "Covert influence infrastructure",
    summary: "Build the documented funding and distribution map without treating editorial similarity as attribution.",
    updated: "Updated 2 hr ago",
    accent: "#748b9b",
    items: {
      Notes: ["Attribution threshold", "Funding evidence", "Replacement domains", "Open questions"],
      Links: ["Treasury designation", "State Department pillars", "EEAS FIMI report", "Platform takedown"],
      Chats: ["Documented edges only", "Find proxy operators", "Model replacement behavior", "Review weak links"],
      Graphs: ["Funding chain", "Proxy publishers", "Video distribution", "Platform exposure"],
    },
  },
  {
    id: "prc-partnerships",
    title: "PRC media partnerships",
    summary: "Map disclosed content relationships, regional distribution, and policy-sensitive commercial entities.",
    updated: "Updated yesterday",
    accent: "#8d5b43",
    items: {
      Notes: ["Disclosure standards", "Regional outlet sample", "Procurement sensitivity", "Translation changes"],
      Links: ["Information environment report", "Media freedom index", "Partner disclosure pages", "Diplomatic account archive"],
      Chats: ["Map content partners", "Compare official language", "Find procurement exposure", "Check attribution limits"],
      Graphs: ["Partner network", "Diplomatic amplification", "Regional audiences", "Commercial sensitivity"],
    },
  },
];

export const assistantDemos = [
  {
    match: "benefit",
    answer: "The strongest direct sensitivity is in export revenue and freight utilization. The model ranks Rosneft and Sovcomflot highest, but it does not infer they promoted the narrative.",
    metric: "88 / 100",
    metricLabel: "modeled benefit sensitivity",
    path: "Futility frame -> enforcement pressure -> export access -> realized revenue",
    forecast: "A fresh tanker designation creates a 74% probability of a 24-hour pickup cycle.",
  },
  {
    match: "biolab",
    answer: "The current spike is a reactivation, not a new allegation. An older political clip is being attached to a new records debate, then distributed through state media and commentary channels.",
    metric: "82%",
    metricLabel: "24-hour propagation forecast",
    path: "Records debate -> recycled clip -> state-media segment -> Western commentary",
    forecast: "Cross-language pickup is likely to persist for seven days if another official statement lands.",
  },
  {
    match: "documented",
    answer: "Documented edges show explicit funding, designations, or sourced entity associations. Scenario edges estimate outcome sensitivity and remain visually dashed throughout Axial.",
    metric: "71",
    metricLabel: "documented source records",
    path: "State direction -> covert funding -> proxy publisher -> distribution",
    forecast: "Replacement infrastructure remains the highest-confidence persistence mechanism.",
  },
];
